### PR TITLE
Create en_gb.json

### PR DESCRIPTION
**Pull request by NatickYT**

### CODE REVIEW

**Comment by NatickYT** [comment]
Adding en_gb.json To 1.18.x

**Comment by MrCrayfish** [comment]
Thank you!

**Comment by MrCrayfish** [comment]
Hey @NatickYT, I'm currently in the process of relicensing Backpacked. I would like your permission to relicense your contributions to Backpacked under LGPLv2.1. Thank you

**Comment by NatickYT** [comment]
Hi @MrCrayfish,
Sorry For The Late Response,
That's Fine With Me And Thanks For Asking First.

**Pull request merged**
