### PR TITLE
Update de_de.json

### PR DESCRIPTION
**Pull request by Fuzss**
Thanks for this amazing update, really impressive and well done!

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Thank you and thank you for the translations!

**Comment by MrCrayfish** [comment]
Hey @Fuzss, I'm currently in the process of relicensing Backpacked. I would like your permission to relicense your contributions to Backpacked under LGPLv2.1. Thank you

**Comment by Fuzss** [comment]
Sure

**Comment by MrCrayfish** [comment]
Thanks for the quick reply.

**Pull request merged**
