### PR TITLE
Update ru_ru.json

### PR DESCRIPTION
**Pull request by vanja-san**

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Thank you!

**Comment by MrCrayfish** [comment]
Hey @vanja-san , I'm currently in the process of relicensing Backpacked. I would like your permission to relicense your contributions to Backpacked under LGPLv2.1. Thank you

**Comment by vanja-san** [comment]
@MrCrayfish ok, no problem.

**Comment by MrCrayfish** [comment]
Thanks for the speedy reply!

**Pull request merged**
